# Comment
CXX=		g++ # Comment
CXXFLAGS=	-g -Wall -std=gnu++11

#all: 		comment
all:		vvvv

solution:	solution.cpp
	$(CXX) solution.cpp $(CXXFLAGS) -o solution
	touch test.xyz
	# touch abc.xyz

vvvv: solution

clean:
	rm solution test.xyz
