t: s
	19

z: y
	25

u: t
	20

m: l
	12

l: k
	11

k: j
	10

d: c
	3

c: b
	2

s: r
	18

v: u
	21

b: a
	1

a:
	0

f: e
	5

e: d
	4

x: w
	23

w: v
	22

r: q
	17

q: p
	16

p: o
	15

o: n
	14

n: m
	13

y: x
	24

j: i
	9

i: h
	8

h: g
	7

g: f
	6
